# permissions for end users to view pizzas.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pizza-viewer-role
rules:
- apiGroups:
  - resturant.foodie.io
  resources:
  - pizzas
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - resturant.foodie.io
  resources:
  - pizzas/status
  verbs:
  - get
