
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - resturant
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resturant
  resources:
  - jobs/status
  verbs:
  - get
- apiGroups:
  - resturant.foodie.io
  resources:
  - pizzas
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - resturant.foodie.io
  resources:
  - pizzas/status
  verbs:
  - get
  - patch
  - update
