apiVersion: resturant.foodie.io/v1
kind: Pizza
metadata:
  name: pizza-my-sample
spec:
  # Add fields here
  toppings:
    - "Cheese"
    - "Chicken"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
          restartPolicy: OnFailure
